[versions]
agp = "8.6.1"
kotlin = "2.1.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.10.1"
navigationCompose = "2.9.5"
composeBom = "2025.09.01"
daggerHilt = "2.57.1"
datastore = "1.1.7"
protobufPlugin = "0.9.5"
protobuf = "3.21.9"
retrofit = "2.9.0"
okhttp3 = "4.11.0"
moshi = "1.15.0"
moshiKotlin = "1.15.0"
kotlinResult = "1.1.18"
timber = "5.0.1"
dokka = "1.8.10"
ksp = "2.1.21-2.0.2"
ktlint = "0.47.1"
kotest = "5.9.1"
kover = "0.9.0-RC"

[libraries]
# Android Core Libraries
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-viemodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx"}
# Jetpack Compose Libraries
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
# Jetpack Compose Navigation
androidx-navigation-compose = { group = "androidx.navigation", name =  "navigation-compose", version.ref = "navigationCompose" }
# Material Icons Extended
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
# Unit Test Libraries
junit = { group = "junit", name = "junit", version.ref = "junit" }
# Android Test Libraries
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
# Dagger Hilt
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHilt" }
# DataStore
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
# Protocol Buffer
protobuf = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
# Retrofit2
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converterMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
# OkHttp
okhttp3 = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
# Moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
# Kotlin Resolt
kotlinResult = { group = "com.michael-bull.kotlin-result", name = "kotlin-result", version.ref = "kotlinResult" }
# Timber
timber ={ group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
# Lint Libraries
ktlint = { group = "com.pinterest", name = "ktlint", version.ref = "ktlint" }
# Kotest
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-compose = {id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Kps
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# Dagger Hilt
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
# Protocol Buffer
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
# Docca(API Documentation)
dokka =  { id = "org.jetbrains.dokka", version.ref = "dokka" }
# Unit Test Coverage Libraries
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
